### PR TITLE
feat/add php refactor for convert arrow function to anonymous function

### PR DESCRIPTION
**Pull request by deshazer**
Hello,

I was in the middle of trying to make something just like this plugin when I came across yours! I was frustrated by the lack of good PHP code action providers. So, I made a PR that adds the ability to convert an arrow function `fn () => ...` to an anonymous function `function() { return ...; }`

You'll notice I also added support for providing a custom formatting function (so I can use my conform.nvim plugin instead of the built-in `vim.lsp.buf.format()`).

In the future, if you're up for it, I'd like to add PHP refactors for: 
1. Converting back from an anonymous function to an arrow function
2. Converting back/forth between ternary and basic if/else statements
3. Any other refactors I find myself doing a lot!

My current work stack is Laravel backend, JS/React frontend. So, I'd be happy to add other refactors for JS as well.

### CODE REVIEW

**Comment by jdrupal-dev** [comment]
@deshazer Thank you for this contribution! You're more than welcome to contribute with more code actions 🚀 

I have updated the PR with a reformatting of the entire plugin (now that we have a stylua conf 😄).

I have renamed the action to match the one I have for JS, and also refactored it, so that is supports toggling to and from arrow function syntax.

Please test my changes and let me know if they work as expected.

**Comment by deshazer** [comment]
Awesome! 🔥🚀

Sorry, I didn't get much of a chance today. But, I did think of a couple of edge cases we might need to account for:

1. When the arrow function has a `use()` clause, we need to remove that (I always forget about those because I wish they didn't exist).
2. More challenging, but it would be cool if we added the `use()` statement back in for the correct variables when converting back to a `function()`. We might have to mark this one as "extra-credit", because I think we'll want the LSP's help to determine if any variable inside the function was declared outside the scope. 🤷‍♂️
3. It's kind of annoying when your anonymous function only has one line, and you can totally convert it to an arrow function, but you plan to ignore the return value. For example:
```
$users->each(function ($user) {
  $user->update( /* ... */);
});
```
This could easily be converted to this, despite not having a return statement.
```
$users->each(fn ($user) => $user->update( /* ... */));
```

**Comment by deshazer** [comment]
Ok, I think I've handled all three of the cases from my previous comment. 

1. Removing the `use` statement was already happening naturally as we converted to an arrow function.
2. I did this *without* using the LSP. All Treesitter, as promised. 👍
3. I also modified this to convert to an arrow function as long as there was only one named child `expreesion_statement` or `return_statement`.

Give it a try and let me know what you think! 👀

**Comment by jdrupal-dev** [comment]
The changes look good!

Thank you for your contribution :smile:

**Pull request merged**
